name: Docs

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - 'docs/*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['stable', 'devel']
    steps:
      - uses: actions/checkout@v1

      - name: Setup nim environment
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Generate docs
        run: |
          nim doc --outdir: docs/plugins src/plugins/plugins.nim
          nim doc --outdir: docs/ecs src/ecs/table.nim
    
      - name: Deploying
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
     
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        