name: Docs

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - 'docs/*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['stable', 'devel']
    steps:
      - uses: actions/checkout@v1

      - name: Setup nim environment
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Generate docs
        run: |
          nim doc --outdir: docs/plugins src/plugins/plugins.nim
          nim doc --outdir: docs/ecs src/ecs/table.nim